import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

const strings = new LocalizedStrings({
 en:{
    "new_version_msg": "New version is available",
    "update": "Update",
    "matchday": "Matchday",
    "score_predicted": "The score is predicted",
    "winner_predicted": "The winner is predicted",
    "winner_or_draw_predicted": "The winner or draw is predicted",
    "draw_predicted" : "A draw is predicted",
    "prediction_was_failed": "Prediction was wrong",
    "main_table": "Main table",
    "player": "Player",
    "pos": "Position",
    "total_short": "Total count of match predictions",
    "pts": "Points",
    "rate": "Accuracy of predictions",
    "place_in_el_torneo": "Place in el Torneo",
    "points": "Points",
    "total": "Total",
    "next": "Next",
    "prev": "Previous",
    "home": "Home",
    "away": "Away",
    "signout": "Sign out",
    "no_matches_found": 'Matches are not available yet.',
    "sign_in_to_predict": 'Sign in to predict',
    "no_pred_for_match": "There are no predictions for this match.",
    "no_live_matches": "There are no live matches yet.",
    "summary": "Summary",
    "predictions": "predictions",
    "top_20_predicts": "Top 20 players predictions",
    "all": "All",
    "no_predicts": "There are no predictions.",
    "prediction": "Prediction",
    "join_now": "Join now",
    "predict": "Predict",
    "delete_acc": "Delete account",
    "yes": "Yes",
    "no": "No",
    "signout_msg": "Are you sure you want to sign out?",
    "delete_acc_msg": "Are you sure you want to delete your account?",
    "sun": "Sun",
    "mon": "Mon",
    "tue": "Tue",
    "wed": "Wed",
    "thu": "Thu",
    "fri": "Fri",
    "sat": "Sat",
    "jan": "Jan",
    "feb": "Feb",
    "mar": "Mar",
    "apr": "Apr",
    "may": "May",
    "jun": "Jun",
    "jul": "Jul",
    "aug": "Aug",
    "sep": "Sep",
    "oct": "Oct",
    "nov": "Nov",
    "dec": "Dec",
    "app_desc": "Experience the thrill of the world’s largest football fan tournament! Compete with fans worldwide in a one-of-a-kind challenge that puts your football knowledge to the test. Predict match outcomes, earn points, and rise through the ranks to become the ultimate football champion.",
    "in_all_leagues": "In all leagues",
    "team": "Team",
    "matches_played": "Matches played",
    "goal_diff": "Goal difference",
    "matches": "Matches",
    "table": "Table",
    "predictions2": "Predictions",
    "statistics": "Statistics",
    "events": "Events",
    "shots_on_target": "Shots on target",
    "shots_off_target": "Shots off target",
    "ball_possession": "Ball possession",
    "fouls": "Fouls",
    "corners": "Corner kicks",
    "offsides": "Offsides",
    "saves": "Goalkeeper saves",
    "goal": "Goal",
    "card": "Card",
    "unlock_all": "Unlock all",
    "unlock_table": "See table",
    "group": "Group",
    "missed_penalty": "Missed penalty",
    "login_desc": "Join the worldwide football prediction tournament!",
    "awards": "Awards for season 24/25",
    "rules": "Rules",
    "points2": "points",
    "point": "point",
    "award_msg": "The top 20 players will be awarded at the end of the season.",
    "see_predictions": "See predictions",
    "handball": "Handball",
    "save": "Save",
    "conn_error": "Please verify your internet connection and refresh.",
    "lineups": "Lineups",
    "substitutes": "Substitutes",
    "managers": "Managers",
    "goalkeeper": "Goalkeeper",
    "defender": "Defender",
    "midfielder": "Midfielder",
    "forward": "Forward",
    "draw": "Draw",
    "unlock_ad_msg": "Watch the ad to view predictions from other users!",
    "predict_ad_msg": "Finish watching the ad to submit your prediction!",
    "predict_edit_ad_msg": "Finish watching the ad to apply your prediction changes!"
  },
  es:{
    "new_version_msg": "Nueva versión disponible.",
    "update": "Actualizar",
    "matchday": "Jornada",
    "score_predicted": "El resultado fue previsto",
    "winner_predicted": "El ganador fue predicho",
    "winner_or_draw_predicted": "Se predijo ganador o empate",
    "draw_predicted" : "El empate estaba previsto",
    "prediction_was_failed": "La predicción falló",
    "main_table": "Mesa principal",
    "pos": "Posición",
    "player": "Jugador",
    "total_short": "Recuento total de predicciones de partidos",
    "pts": "Puntos",
    "rate": "Precisión de las predicciones",
    "place_in_el_torneo": "Posición en el Torneo",
    "points": "Puntos",
    "total": "Total",
    "next": "Siguiente",
    "prev": "Anterior",
    "home": "Local",
    "away": "Visitante",
    "signout": "Cerrar sesión",
    "no_matches_found": 'Los partidos aún no están disponibles.',
    "sign_in_to_predict": 'Inicia sesión para predecir',
    "no_pred_for_match": "No hay predicciones para este partido.",
    "no_live_matches": "Aún no hay partidos en vivo.",
    "summary": "Sumario",
    "predictions": "predicciones",
    "top_20_predicts": "Predicciones de los 20 mejores jugadores",
    "all": "Todo",
    "no_predicts": "No hay predicciones.",
    "prediction": "Predicción",
    "join_now": "Únete ahora",
    "predict": "Pronóstico",
    "delete_acc": "Eliminar cuenta",
    "yes": "Sí",
    "no": "No",
    "signout_msg": "Estás seguro de que quieres cerrar sesión?",
    "delete_acc_msg": "Estás seguro de que quieres eliminar tu cuenta?",
    "sun": "Dom",
    "mon": "Lun",
    "tue": "Mar",
    "wed": "Mié",
    "thu": "Jue",
    "fri": "Vie",
    "sat": "Sáb",
    "jan": "Ene",
    "feb": "Feb",
    "mar": "Mar",
    "apr": "Abr",
    "may": "May",
    "jun": "Jun",
    "jul": "Jul",
    "aug": "Ago",
    "sep": "Sep",
    "oct": "Oct",
    "nov": "Nov",
    "dec": "Dic",
    "app_desc": "Vive la emoción del torneo de fútbol más grande del mundo. Compite con fanáticos de todo el mundo en un desafío único que pone a prueba tus conocimientos sobre fútbol. Predice resultados de partidos, gana puntos y asciende en la clasificación para convertirte en el campeón de fútbol definitivo.",
    "in_all_leagues": "En todas las ligas",
    "team": "Equipo",
    "matches_played": "Partidos jugados",
    "goal_diff": "Diferencia de goles",
    "matches": "Partidos",
    "table": "Tabla",
    "predictions2": "Pronósticos",
    "statistics": "Estadística",
    "events": "Eventos",
    "shots_on_target": "Tiros a puerta",
    "shots_off_target": "Tiros fuera",
    "ball_possession": "Posesión del balón",
    "fouls": "Faltas",
    "corners": "Tiros de esquina",
    "offsides": "Fuera de juego",
    "saves": "Paradas",
    "goal": "Gol",
    "card": "Tarjeta",
    "unlock_all": "Desbloquear todo",
    "unlock_table": "Ver tabla",
    "group": "Grupo",
    "missed_penalty": "Penalti fallado",
    "login_desc": "¡Únete al torneo mundial de predicciones de fútbol!",
    "awards": "Premios de la temporada 24/25",
    "rules": "Reglas",
    "points2": "puntos",
    "point": "punto",
    "award_msg": "Los 20 mejores jugadores serán premiados al final de la temporada.",
    "see_predictions": "Ver previsiones",
    "handball": "Falta de mano",
    "save": "Guardar",
    "conn_error": "Por favor, verifica tu conexión a Internet y actualiza.",
    "lineups": "Alineaciones",
    "substitutes": "Suplentes",
    "managers": "Entrenadores",
    "goalkeeper": "Portero",
    "defender": "Defensa",
    "midfielder": "Centrocampista",
    "forward": "Delantero",
    "draw": "Empate",
    "unlock_ad_msg": "Mira el anuncio para ver las predicciones de otros usuarios!",
    "predict_ad_msg": "Termina de ver el anuncio para enviar tu predicción!",
    "predict_edit_ad_msg": "Termina de ver el anuncio para aplicar los cambios en tu predicción!"
  },
  fr:{
    "new_version_msg": "Nouvelle version disponible.",
    "update": "Mettre à jour",
    "matchday": "Journée",
    "score_predicted": "Le score a été prédit",
    "winner_predicted": "Le vainqueur a été prédit",
    "winner_or_draw_predicted": "Vainqueur ou match nul prédit",
    "draw_predicted": "Match nul prédit",
    "prediction_was_failed": "La prédiction a échoué",
    "main_table": "Table principale",
    "pos": "Position",
    "player": "Joueur",
    "total_short": "Nombre total de prédictions de match",
    "pts": "Points",
    "rate": "Précision des prédictions",
    "place_in_el_torneo": "Position dans el Torneo",
    "points": "Points",
    "total": "Total",
    "next": "Suivant",
    "prev": "Précédent",
    "home": "Domicile",
    "away": "Extérieur",
    "signout": "Déconnexion",
    "no_matches_found": 'Les matches ne sont pas encore disponibles.',
    "sign_in_to_predict": 'Identifiez-vous pour prédire',
    "no_pred_for_match": "Il n'y a pas de pronostics pour ce match.",
    "no_live_matches": "Il n'y a pas encore de matchs en direct.",
    "summary": "Sommaire",
    "predictions": "prédictions",
    "top_20_predicts": "Prédictions des 20 meilleurs joueurs",
    "all": "Tout",
    "no_predicts": "Il n'y a pas de prédictions.",
    "prediction": "Prédiction",
    "join_now": "Rejoindre",
    "predict": "Prévision",
    "delete_acc": "Supprimer le compte",
    "yes": "Oui",
    "no": "Non",
    "signout_msg": "Etes-vous sûr de vouloir vous déconnecter?",
    "delete_acc_msg": "Etes-vous sûr de vouloir supprimer votre compte?",
    "sun": "Dim",
    "mon": "Lun",
    "tue": "Mar",
    "wed": "Mer",
    "thu": "Jeu",
    "fri": "Ven",
    "sat": "Sam",
    "jan": "Jan",
    "feb": "Fév",
    "mar": "Mar",
    "apr": "Avr",
    "may": "Mai",
    "junn": "Jui",
    "jull": "Jui",
    "aug": "Aoû",
    "sep": "Sep",
    "oct": "Oct",
    "nov": "Nov",
    "dec": "Déc",
    "app_desc": "Vivez le frisson du plus grand tournoi de fans de football au monde ! Affrontez des fans du monde entier dans un défi unique qui met vos connaissances du football à l'épreuve. Prédisez les résultats des matchs, gagnez des points et gravissez les échelons pour devenir le champion de football ultime." ,
    "in_all_leagues": "Dans toutes les ligues",
    "team": "Équipe",
    "matches_played": "Matchs joués",
    "goal_diff": "Différence de buts",
    "matches": "Matchs",
    "table": "Tableau",
    "predictions2": "Prédictions",
    "statistics": "Statistiques",
    "events": "Événements",
    "shots_on_target": "Tirs cadrés",
    "shots_off_target": "Tirs non cadrés",
    "ball_possession": "Possession du ballon",
    "fouls": "Fautes",
    "corners": "Corners",
    "offsides": "Hors-jeu",
    "saves": "Arrêts",
    "goal": "But",
    "card": "Carton",
    "unlock_all": "Débloquer tout",
    "unlock_table": "Voir le tableau",
    "group": "Groupe",
    "missed_penalty": "Pénalité manquée",
    "login_desc": "Rejoignez le tournoi mondial de pronostics de football !",
    "awards": "Récompenses pour la saison 24/25",
    "rules": "Règles",
    "points2": "points",
    "point": "point",
    "award_msg": "Les 20 meilleurs joueurs seront récompensés à la fin de la saison.",
    "see_predictions": "Voir les prévisions",
    "handball": "Main",
    "save": "Sauvegarder",
    "conn_error": "Veuillez vérifier votre connexion Internet et rafraîchir l'application.",
    "lineups": "Alignements",
    "substitutes": "Remplaçants",
    "managers": "Entraîneurs",
    "goalkeeper": "Gardien",
    "defender": "Défenseur",
    "midfielder": "Milieu de terrain",
    "forward": "Attaquant",
    "draw": "Match nul",
    "unlock_ad_msg": "Regardez la publicité pour voir les prédictions des autres utilisateurs !",
    "predict_ad_msg": "Terminez de regarder la publicité pour soumettre votre prédiction !",
    "predict_edit_ad_msg": "Terminez de regarder la publicité pour appliquer vos modifications de prédiction !"
  },
  it:{
    "new_version_msg": "Nuova versione disponibile.",
    "update": "Aggiorna",
    "matchday": "Giornata",
    "score_predicted": "Il punteggio è stato predetto",
    "winner_predicted": "Il vincitore è stato predetto",
    "winner_or_draw_predicted": "Vincitore o pareggio predetto",
    "draw_predicted": "Pareggio previsto",
    "prediction_was_failed": "La previsione è fallita",
    "main_table": "Tabella principale",
    "pos": "Posizione",
    "player": "Giocatore",
    "total_short": "Conteggio totale delle previsioni delle partite",
    "pts": "Punti",
    "rate": "Precisione delle previsioni",
    "place_in_el_torneo": "Posizione in el Torneo",
    "points": "Punti",
    "total": "Totale",
    "next": "Successivo",
    "prev": "Precedente",
    "home": "Casa",
    "away": "Trasferta",
    "signout": "Disconnetti",
    "no_matches_found": 'Le partite non sono ancora disponibili.',
    "sign_in_to_predict": 'Accedi per prevedere',
    "no_pred_for_match": "Non ci sono pronostici per questa partita.",
    "no_live_matches": "Non ci sono ancora partite in diretta.",
    "summary": "Sommario",
    "predictions": "predizioni",
    "top_20_predicts": "Pronostici sui 20 migliori giocatori",
    "all": "Tutto",
    "no_predicts": "Non ci sono previsioni.",
    "prediction": "Pronostico",
    "join_now": "Iscriviti ora",
    "predict": "Previsione",
    "delete_acc": "Elimina account",
    "yes": "SÌ",
    "no": "No",
    "signout_msg": "Sei sicuro di voler uscire?",
    "delete_acc_msg": "Sei sicuro di voler eliminare il tuo account?",
    "sun": "Dom",
    "mon": "Lun",
    "tue": "Mar",
    "wed": "Mer",
    "thu": "Gio",
    "fri": "Ven",
    "sat": "Sab",
    "jan": "Gen",
    "feb": "Feb",
    "mar": "Mar",
    "apr": "Apr",
    "may": "Mag",
    "jun": "Giu",
    "jul": "Lug",
    "aug": "Ago",
    "sep": "Set",
    "oct": "Ott",
    "nov": "Nov",
    "dec": "Dic",
    "app_desc": "Vivi l'emozione del più grande torneo di tifosi di calcio del mondo! Sfida i tifosi di tutto il mondo in una sfida unica nel suo genere che mette alla prova la tua conoscenza del calcio. Prevedi i risultati delle partite, guadagna punti e scala le classifiche per diventare il campione di calcio definitivo.",
    "in_all_leagues": "In tutti i campionati",
    "team": "Squadra",
    "matches_played": "Partite giocate",
    "goal_diff": "Differenza reti",
    "matches": "Partite",
    "table": "Tabella",
    "predictions2": "Previsioni",
    "statistics": "Statistiche",
    "events": "Eventi",
    "shots_on_target": "Tiri in porta",
    "shots_off_target": "Tiri fuori",
    "ball_possession": "Possesso palla",
    "fouls": "Falli",
    "corners": "Calci d'angolo",
    "offsides": "Fuorigioco",
    "saves": "Parate",
    "goal": "Gol",
    "card": "Cartellino",
    "unlock_all": "Sblocca tutto",
    "unlock_table": "Visualizza tabella",
    "group": "Gruppo",
    "missed_penalty": "Rigore sbagliato",
    "login_desc": "Unisciti al torneo mondiale di pronostici calcistici!",
    "awards": "Premi per la stagione 24/25",
    "rules": "Regole",
    "points2": "punti",
    "point": "punto",
    "award_msg": "I migliori 20 giocatori saranno premiati alla fine della stagione.",
    "see_predictions": "Visualizza le previsioni",
    "handball": "Mano",
    "save": "Salva",
    "conn_error": "Si prega di verificare la connessione Internet e aggiornare l'app.",
    "lineups": "Formazioni",
    "substitutes": "Riserva",
    "managers": "Allenatori",
    "goalkeeper": "Portiere",
    "defender": "Difensore",
    "midfielder": "Centrocampista",
    "forward": "Attaccante",
    "draw": "Pareggio",
    "unlock_ad_msg": "Guarda l'annuncio per visualizzare le previsioni degli altri utenti!",
    "predict_ad_msg": "Finisci di guardare l'annuncio per inviare la tua previsione!",
    "predict_edit_ad_msg": "Finisci di guardare l'annuncio per applicare le modifiche alla tua previsione!"
  },
  ru:{
    "new_version_msg": "Доступна новая версия.",
    "update": "Обновить",
    "matchday": "Тур",
    "score_predicted": "Предсказан счёт",
    "winner_predicted": "Предсказан победитель",
    "winner_or_draw_predicted": "Предсказан победитель или ничья",
    "draw_predicted": "Ничья предсказана",
    "prediction_was_failed": "Прогноз не сбылся",
    "main_table": "Основная таблица",
    "pos": "Позиция",
    "player": "Игрок",
    "total_short": "Общее количество прогнозов матчей",
    "pts": "Очки",
    "rate": "Точность прогнозов",
    "place_in_el_torneo": "Позиция в el Torneo",
    "points": "Очки",
    "total": "Всего",
    "next": "Следующий",
    "prev": "Предыдущий",
    "home": "Дома",
    "away": "В гостях",
    "signout": "Выйти",
    "no_matches_found": 'Нет матчей.',
    "sign_in_to_predict": 'Войдите, чтобы сделать прогноз',
    "no_pred_for_match": "На этот матч нет прогнозов.",
    "no_live_matches": "Пока нет прямых трансляций.",
    "summary": "Краткое содержание",
    "predictions": "прогнозов",
    "top_20_predicts": "Прогнозы 20 лучших игроков",
    "all": "Все",
    "no_predicts": "Прогнозов нет.",
    "prediction": "Прогноз",
    "join_now": "Войти сейчас",
    "predict": "Прогнозировать",
    "delete_acc": "Удалить аккаунт",
    "yes": "Да",
    "no": "Нет",
    "signout_msg": "Вы уверены, что хотите выйти?",
    "delete_acc_msg": "Вы действительно хотите удалить свой аккаунт?",
    "sun": "Вс",
    "mon": "Пн",
    "tue": "Вт",
    "wed": "Ср",
    "thu": "Чт",
    "fri": "Пт",
    "sat": "Сб",
    "jan": "Янв",
    "feb": "Фев",
    "mar": "Мар",
    "apr": "Апр",
    "may": "Май",
    "jun": "Июн",
    "jul": "Июл",
    "aug": "Авг",
    "sep": "Сен",
    "oct": "Окт",
    "nov": "Ноя",
    "dec": "Дек",
    "app_desc": "Испытайте острые ощущения на крупнейшем в мире турнире футбольных фанатов! Соревнуйтесь с болельщиками по всему миру в уникальном испытании, которое проверяет ваши футбольные знания. Предсказывайте результаты матчей, зарабатывайте очки и поднимайтесь по карьерной лестнице, чтобы стать абсолютным чемпионом по футболу.",
    "in_all_leagues": "Во всех лигах",
    "team": "Команда",
    "matches_played": "Сыграно матчей",
    "goal_diff": "Разница мячей",
    "matches": "Матчи",
    "table": "Таблица",
    "predictions2": "Прогнозы",
    "statistics": "Статистика",
    "events": "События",
    "shots_on_target": "Удары в створ",
    "shots_off_target": "Удары мимо",
    "ball_possession": "Владение мячом",
    "fouls": "Нарушения",
    "corners": "Угловые",
    "offsides": "Офсайды",
    "saves": "Сейвы",
    "goal": "Гол",
    "card": "Карточка",
    "unlock_all": "Разблокировать все",
    "unlock_table": "Посмотреть таблицу",
    "group": "Группа",
    "missed_penalty": "Нереализованный",
    "login_desc": "Присоединяйтесь к всемирному футбольному турниру прогнозов!",
    "awards": "Награды сезона 24/25",
    "rules": "Правила",
    "points2": "очка",
    "point": "очко",
    "award_msg": "20 лучших игроков будут награждены в конце сезона.",
    "see_predictions": "Посмотреть прогнозы",
    "handball": "Игра рукой",
    "save": "Сохранить",
    "conn_error": "Пожалуйста, проверьте подключение к Интернету и обновите.",
    "lineups": "Составы",
    "substitutes": "Запасные",
    "managers": "Тренеры",
    "goalkeeper": "Вратарь",
    "defender": "Защитник",
    "midfielder": "Полузащитник",
    "forward": "Нападающий",
    "draw": "Ничья",
    "unlock_ad_msg": "Посмотрите рекламу, чтобы увидеть прогнозы других пользователей!",
    "predict_ad_msg": "Закончите просмотр рекламы, чтобы отправить свой прогноз!",
    "predict_edit_ad_msg": "Закончите просмотр рекламы, чтобы применить изменения в вашем прогнозе!"

  },
  pt:{
    "new_version_msg": "Nova versão disponível.",
    "update": "Atualizar",
    "matchday": "Jornada",
    "score_predicted": "O resultado foi previsto",
    "winner_predicted": "O vencedor foi previsto",
    "winner_or_draw_predicted": "Vencedor ou empate previsto",
    "draw_predicted": "Empate previsto",
    "prediction_was_failed": "A previsão falhou",
    "main_table": "Tabela principal",
    "pos": "Posição",
    "player": "Jogador",
    "total_short": "Contagem total de previsões",
    "pts": "Pontos",
    "rate": "Precisão das previsões",
    "place_in_el_torneo": "Posição no el Torneo",
    "points": "Pontos",
    "total": "Total",
    "next": "Próximo",
    "prev": "Anterior",
    "home": "Casa",
    "away": "Fora",
    "signout": "Sair",
    "no_matches_found": 'As partidas ainda não estão disponíveis.',
    "sign_in_to_predict": 'Faça login para prever',
    "no_pred_for_match": "Não há previsões para esta partida.",
    "no_live_matches": "Ainda não há partidas ao vivo.",
    "summary": "Resumo",
    "predictions": "prognóstico",
    "top_20_predicts": "Previsões dos 20 melhores jogadores",
    "all": "Tudo",
    "no_predicts": "Não há previsões.",
    "prediction": "Previsão",
    "join_now": "Registe-se agora",
    "predict": "Previsão",
    "delete_acc": "Excluir conta",
    "yes": "Sim",
    "no": "Não",
    "signout_msg": "Tem certeza de que deseja sair?",
    "delete_acc_msg": "Tem certeza de que deseja excluir sua conta?",
    "sun": "Dom",
    "mon": "Seg",
    "tue": "Ter",
    "wed": "Qua",
    "thu": "Qui",
    "fri": "Sex",
    "sat": "Sáb",
    "jan": "Jan",
    "feb": "Fev",
    "mar": "Mar",
    "apr": "Abr",
    "may": "Mai",
    "jun": "Jun",
    "jul": "Jul",
    "aug": "Ago",
    "sep": "Set",
    "oct": "Out",
    "nov": "Nov",
    "dec": "Dez",
    "app_desc": "Experimente a emoção do maior torneio de fãs de futebol do mundo! Compita com fãs do mundo todo em um desafio único que coloca seu conhecimento de futebol à prova. Preveja resultados de partidas, ganhe pontos e suba na classificação para se tornar o campeão de futebol definitivo." ,
    "in_all_leagues": "Em todas as ligas",
    "team": "Time",
    "matches_played": "Partidas jogadas",
    "goal_diff": "Diferença de gols",
    "matches": "Partidas",
    "table": "Tabela",
    "predictions2": "Previsões",
    "statistics": "Estatísticas",
    "events": "Eventos",
    "shots_on_target": "Chutes no alvo",
    "shots_off_target": "Chutes fora",
    "ball_possession": "Posse de bola",
    "fouls": "Faltas",
    "corners": "Escanteios",
    "offsides": "Impedimentos",
    "saves": "Defesas",
    "goal": "Gol",
    "card": "Cartão",
    "unlock_all": "Desbloquear tudo",
    "unlock_table": "Ver tabela",
    "group": "Grupo",
    "missed_penalty": "Penalidade perdida",
    "login_desc": "Participe do torneio mundial de previsões de futebol!",
    "awards": "Prêmios para a temporada 24/25",
    "rules": "Regras",
    "points2": "pontos",
    "point": "ponto",
    "award_msg": "Os 20 melhores jogadores serão premiados no final da temporada.",
    "see_predictions": "Ver previsões",
    "handball": "Mão na bola",
    "save": "Salvar",
    "conn_error": "Por favor, verifique sua conexão à Internet e atualize o aplicativo.",
    "lineups": "Escalações",
    "substitutes": "Substitutos",
    "managers": "Treinadores",
    "goalkeeper": "Goleiro",
    "defender": "Zagueiro",
    "midfielder": "Meio-campista",
    "forward": "Atacante",
    "draw": "Empate",
    "unlock_ad_msg": "Assista ao anúncio para ver as previsões de outros usuários!",
    "predict_ad_msg": "Termine de assistir ao anúncio para enviar sua previsão!",
    "predict_edit_ad_msg": "Termine de assistir ao anúncio para aplicar suas alterações na previsão!"

  },
  de:{
    "new_version_msg": "Neue Version verfügbar.",
    "update": "Aktualisieren",
    "matchday": "Spieltag",
    "score_predicted": "Ergebnis vorhergesagt",
    "winner_predicted": "Gewinner vorhergesagt",
    "winner_or_draw_predicted": "Gewinner oder Unentschieden vorhergesagt",
    "draw_predicted": "Unentschieden vorhergesagt",
    "prediction_was_failed": "Die Vorhersage ist fehlgeschlagen",
    "main_table": "Haupttabelle",
    "pos": "Position",
    "player": "Spieler",
    "total_short": "Gesamtzahl der Vorhersagen",
    "pts": "Punkte",
    "rate": "Genauigkeit der Vorhersagen",
    "place_in_el_torneo": "Platzierung in el Torneo",
    "points": "Punkte",
    "total": "Gesamt",
    "next": "Nächstes",
    "prev": "Vorheriges",
    "home": "Heim",
    "away": "Auswärts",
    "signout": "Abmelden",
    "no_matches_found": 'Übereinstimmungen sind noch nicht verfügbar.',
    "sign_in_to_predict": 'Machen Sie eine Prognose',
    "no_pred_for_match": "Es gibt keine Vorhersagen für dieses Spiel.",
    "no_live_matches": "Es gibt noch keine Live-Übertragungen.",
    "summary": "Zusammenfassung",
    "predictions": "prognosen",
    "top_20_predicts": "Top-20-Spielervorhersagen",
    "all": "Alle",
    "no_predicts": "Keine Prognosen.",
    "prediction": "Vorhersage",
    "join_now": "Jetzt anmelden",
    "predict": "Prognostizieren",
    "delete_acc": "Konto löschen",
    "yes": "Ja",
    "no": "Nein",
    "signout_msg": "Möchten Sie sich wirklich abmelden?",
    "delete_acc_msg": "Möchten sie ihr konto wirklich löschen?",
    "sun": "So",
    "mon": "Mo",
    "tue": "Di",
    "wed": "Mi",
    "thu": "Do",
    "fri": "Fr",
    "sat": "Sa",
    "jan": "Jan",
    "feb": "Feb",
    "mar": "Mär",
    "apr": "Apr",
    "may": "Mai",
    "jun": "Jun",
    "jul": "Jul",
    "aug": "Aug",
    "sep": "Sep",
    "oct": "Okt",
    "nov": "Nov",
    "dec": "Dez",
    "app_desc": "Erleben Sie den Nervenkitzel des größten Fußballfan-Turniers der Welt! Messen Sie sich mit Fans aus aller Welt in einer einzigartigen Herausforderung, bei der Sie Ihr Fußballwissen auf die Probe stellen. Sagen Sie Spielergebnisse voraus, sammeln Sie Punkte und steigen Sie in den Rängen auf, um der ultimative Fußballmeister zu werden.",
    "in_all_leagues": "In allen Ligen",
    "team": "Mannschaft",
    "matches_played": "Gespielte Spiele",
    "goal_diff": "Tordifferenz",
    "matches": "Spiele",
    "table": "Tabelle",
    "predictions2": "Prognosen",
    "statistics": "Statistiken",
    "events": "Ereignisse",
    "shots_on_target": "Schüsse aufs Tor",
    "shots_off_target": "Schüsse daneben",
    "ball_possession": "Ballbesitz",
    "fouls": "Fouls",
    "corners": "Ecken",
    "offsides": "Abseits",
    "saves": "Paraden",
    "goal": "Tor",
    "card": "Karte",
    "unlock_all": "Alles freischalten",
    "unlock_table": "Tabelle ansehen",
    "group": "Gruppe",
    "missed_penalty": "Verschossener",
    "login_desc": "Nehmen Sie am weltweiten Fußball-Tippturnier teil!",
    "awards": "Auszeichnungen für Saison 24/25",
    "rules": "Regeln",
    "points2": "Punkte",
    "point": "Punkt",
    "award_msg": "Die besten 20 Spieler werden am Ende der Saison ausgezeichnet.",
    "see_predictions": "Prognosen anzeigen",
    "handball": "Handspiel",
    "save": "Speichern",
    "conn_error": "Bitte überprüfen Sie Ihre Internetverbindung und aktualisieren Sie die App.",
    "lineups": "Aufstellungen",
    "substitutes": "Ersatzspieler",
    "managers": "Trainer",
    "goalkeeper": "Torwart",
    "defender": "Verteidiger",
    "midfielder": "Mittelfeldspieler",
    "forward": "Stürmer",
    "draw": "Unentschieden",
    "unlock_ad_msg": "Sieh dir die Werbung an, um die Vorhersagen anderer Benutzer zu sehen!",
    "predict_ad_msg": "Beende das Ansehen der Werbung, um deine Vorhersage abzugeben!",
    "predict_edit_ad_msg": "Beende das Ansehen der Werbung, um deine Änderungen an der Vorhersage anzuwenden!"

  },
  hr:{
    "new_version_msg": "Dostupna nova verzija.",
    "update": "Ažuriraj",
    "matchday": "Kolo",
    "score_predicted": "Rezultat je predviđen",
    "winner_predicted": "Pobjednik je predviđen",
    "winner_or_draw_predicted": "Predviđen pobjednik ili neriješeno",
    "draw_predicted": "Neriješeno predviđeno",
    "prediction_was_failed": "Predviđanje nije uspjelo",
    "main_table": "Glavna tablica",
    "pos": "Položaj",
    "player": "Igrač",
    "total_short": "Ukupan broj predviđanja",
    "pts": "Bodovi",
    "rate": "Točnost predviđanja",
    "place_in_el_torneo": "Pozicija u el Torneo",
    "points": "Bodovi",
    "total": "Ukupno",
    "next": "Sljedeći",
    "prev": "Prethodni",
    "home": "Domaći",
    "away": "Gosti",
    "signout": "Odjava",
    "no_matches_found": 'Podudaranja još nisu dostupna.',
    "sign_in_to_predict": 'Prijavite se da napravite predviđanje',
    "no_pred_for_match": "Nema predviđanja za ovu utakmicu.",
    "no_live_matches": "Još nema izravnih prijenosa.",
    "summary": "Sažetak",
    "predictions": "predviđanja",
    "top_20_predicts": "Top 20 predviđanja igrača",
    "all": "Sve",
    "no_predicts": "Bez prognoza.",
    "prediction": "Prognoza",
    "join_now": "Prijavite se",
    "predict": "Prognoza",
    "delete_acc": "Izbriši račun",
    "yes": "Da",
    "no": "Ne",
    "signout_msg": "Jeste li sigurni da se želite odjaviti?",
    "delete_acc_msg": "Jeste li sigurni da želite izbrisati svoj račun?",
    "sun": "Ned",
    "mon": "Pon",
    "tue": "Uto",
    "wed": "Sri",
    "thu": "Čet",
    "fri": "Pet",
    "sat": "Sub",
    "jan": "Sij",
    "feb": "Vel",
    "mar": "Ožu",
    "apr": "Tra",
    "may": "Svi",
    "jun": "Lip",
    "jul": "Srp",
    "aug": "Kol",
    "sep": "Ruj",
    "oct": "Lis",
    "nov": "Stu",
    "dec": "Pro",
    "app_desc": "Doživite uzbuđenje najvećeg svjetskog turnira nogometnih navijača! Natječite se s navijačima diljem svijeta u jedinstvenom izazovu koji stavlja vaše nogometno znanje na test. Predvidite ishode utakmica, zaradite bodove i napredujte u ljestvici kako biste postali ultimativni nogometni prvak.",
    "in_all_leagues": "U svim ligama",
    "team": "Tim",
    "matches_played": "Odigrane utakmice",
    "goal_diff": "Razlika u golovima",
    "matches": "Podudaranja",
    "table": "Tablica",
    "predictions2": "Prognoze",
    "statistics": "Statistika",
    "events": "Događaji",
    "shots_on_target": "Pogodci u okvir gola",
    "shots_off_target": "Pogodci izvan okvira",
    "ball_possession": "Posjed lopte",
    "fouls": "Prekršaji",
    "corners": "Korneri",
    "offsides": "Zaleđa",
    "saves": "Obrane",
    "goal": "Gol",
    "card": "Kartica",
    "unlock_all": "Otključaj sve",
    "unlock_table": "Pogledaj tablicu",
    "group": "Skupina",
    "missed_penalty": "Promašeni penal",
    "login_desc": "Pridružite se svjetskom turniru nogometnih predviđanja!",
    "awards": "Nagrade za sezonu 24/25",
    "rules": "Pravila",
    "points2": "bodovi",
    "point": "bodova",
    "award_msg": "Prvih 20 igrača bit će nagrađeni na kraju sezone.",
    "see_predictions": "Pogledajte prognoze",
    "handball": "Igra rukom",
    "save": "Spremi",
    "conn_error": "Molimo provjerite svoju internetsku vezu i osvježite aplikaciju.",
    "lineups": "Postave",
    "substitutes": "Rezervni igrači",
    "managers": "Treneri",
    "goalkeeper": "Golman",
    "defender": "Branič",
    "midfielder": "Srednji vezni",
    "forward": "Napadač",
    "draw": "Neriješeno",
    "unlock_ad_msg": "Pogledajte oglas kako biste vidjeli predikcije drugih korisnika!",
    "predict_ad_msg": "Završite gledanje oglasa kako biste poslali svoju predikciju!",
    "predict_edit_ad_msg": "Završite gledanje oglasa kako biste primijenili promjene na svojoj predikciji!"

  },
  


});

export default strings;